##############################    ENDPOINTS USER    ##############################

### Crear / Registrar usuario
POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
  "firstName": "Nico",
  "lastName": "Laza",
  "phoneNumber": "55555789",
  "email": "Nico@gmail.com",
  "password": "2222"

}

### Obtener usuarios
GET http://localhost:3030/api/user/

### Obtener usuario por su id

GET http://localhost:3030/api/user/6



### Modificar usuario put
PUT http://localhost:3030/api/user/5
Content-Type: application/json

{
  "firstName": "antonio",
  "lastName": "rico",
  "phoneNumber": "111111111",
  "email": "antonio@gmail.com",
  "pass": "1111"
}


### Modificar usuario patch
PATCH http://localhost:3030/api/user/5
Content-Type: application/json

{
  "lastName": "Martinez",
  "phoneNumber": "88232542588"
}

### Login que devuelve el jwt
### Login
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "pepdderodaaa@gmail.com",
  "password": "123456"
}

### Obtener usuarios con jwt
GET http://localhost:3030/api/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJlbWFpbCI6Imp3dHRlc3QxQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTUzODU0MCwiZXhwIjoxNzE1NTQyMTQwfQ.acg58ni5p1k1D-Q_7Lxt3dSH1Un23IiHQVWCqtA_BkM


################## ACTIVITIES  ##################

### Crear / Registrar actividades
POST http://localhost:3030/api/activity/register
Content-Type: application/json

{
  "idGroup": 12,
  "name": "BOLICHE",
  "amount": "60",
  "type": "1",
  "date": "2024-05-01"
}


### Obtener actividades
GET http://localhost:3030/api/activity/

### Obtener actividades por su id
GET http://localhost:3030/api/activity/1


### Modificar actividades put
PUT http://localhost:3030/api/activity/1
Content-Type: application/json

{
  "name": "Vacaciones Ibiza",
  "amount": "333",
  "type": "0",
  "date": "2023-08-01"
}

### Modificar actividades patch (MIDDLEWARE)
PATCH http://localhost:3030/api/activity/1
Content-Type: application/json

{
 "name": "Vacaciones Marbella",
  "amount": "213"
}

### eliminar actividad (MIDDLEWARE)
DELETE  http://localhost:3030/api/activity/1


##############################    ENDPOINTS USER    ##############################

### Añade usuarios a una activdad
POST http://localhost:3030/api/activity/add-users
Content-Type: application/json

{
    "idActivity": 1,
    "userIds": [1, 2]
}

### Actualiza usuarios de una actividad
PATCH http://localhost:3030/api/activity/4/update-users
Content-Type: application/json

{
  "userIds": [6, 9]
}

### Obtiene los usuarios de una actividad
GET http://localhost:3030/api/activity/4/users




##############################    ENDPOINTS GROUPS    ##############################

### Crear grupos
POST http://localhost:3030/api/group/register/3
Content-Type: application/json

{
  "name": "Los Angeles"
}

###OBTENER GRUPOS
GET http://localhost:3030/api/group/


### Obtener GRUPO por su id
GET http://localhost:3030/api/group/5



### Modificar GRUPO patch
PATCH http://localhost:3030/api/group/7
Content-Type: application/json

{
  "name": "Viaje Rio CLARO"
  
}

### Modificar GRUPO patch
DELETE  http://localhost:3030/api/group/12

##############################    ENDPOINTS user_has_groups    ##############################
### Añade un usuario a un grupo
POST http://localhost:3030/api/group/11/add_user
Content-Type: application/json

{
    "userIds":[3,7]
}

###Busca usuarios en un grupo
GET http://localhost:3030/api/group/11/users
Content-Type: application/json

###Recupera grupos de un usuario
GET http://localhost:3030/api/group/users/3/group


###Recupera ACTIVIDAD de un grupo
GET http://localhost:3030/api/group/11/activity


###Recupera PAGOS de un grupo DE TODAS LAS ACTIVIDADES DEL GRUPO
GET http://localhost:3030/api/group/11/payment




Content-Type: application/json

###Quita algunos usuarios y agrega otros
PATCH http://localhost:3030/api/group/11/users/change
Content-Type: application/json

{
    "usersIn":[7],
    "usersOut":[6]
}








