##############################    ENDPOINTS USER    ##############################

### Crear / Registrar usuario
POST http://localhost:3030/api/auth/register
Content-Type: application/json

{
  "firstName": "pepas",
  "lastName": "antonia",
  "phoneNumber": "123456789",
  "email": "pepasadddd22s@gmail.com",
  "password": "1111"

}

### Obtener usuarios
GET http://localhost:3030/api/user/

### Obtener usuario por su id

GET http://localhost:3030/api/user/14



### Modificar usuario put
PUT http://localhost:3030/api/user/5
Content-Type: application/json

{
  "firstName": "antonio",
  "lastName": "toni",
  "phoneNumber": "111111111",
  "email": "antonio@gmail.com",
  "pass": "1111"
}


### Modificar usuario patch
PATCH http://localhost:3030/api/user/5
Content-Type: application/json

{
  "lastName": "Martinez",
  "phoneNumber": "88232542588"
}

### Login que devuelve el jwt
### Login
POST http://localhost:3030/api/auth/login
Content-Type: application/json

{
  "email": "pepdderodaaa@gmail.com",
  "password": "123456"
}

### Obtener usuarios con jwt
GET http://localhost:3030/api/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo5LCJlbWFpbCI6Imp3dHRlc3QxQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcxNTUzODU0MCwiZXhwIjoxNzE1NTQyMTQwfQ.acg58ni5p1k1D-Q_7Lxt3dSH1Un23IiHQVWCqtA_BkM


################## ACTIVITIES  ##################

### Crear / Registrar actividades
POST http://localhost:3030/api/activity/register
Content-Type: application/json

{
  "idGroup": 1,
 "name": "Vacas1",
  "amount": "222",
  "type": "1",
  "date": "2024-05-01"
}




### Obtener actividades
GET http://localhost:3030/api/activity/

### Obtener actividades por su id
GET http://localhost:3030/api/activity/1


### Modificar actividades put
PUT http://localhost:3030/api/activity/8
Content-Type: application/json

{
  "name": "Vacaciones Ibiza",
  "amount": "333",
  "type": "0",
  "date": "2023-08-01"
}

### Modificar actividades patch
PATCH http://localhost:3030/api/activity/1
Content-Type: application/json

{
 "name": "Vacaciones Marbella",
  "amount": "213"
}

### eliminar actividad 
DELETE  http://localhost:3030/api/activity/9


##############################    ENDPOINTS USER    ##############################

##############################    ENDPOINTS GROUPS    ##############################

### Crear grupos
POST http://localhost:3030/api/group/register
Content-Type: application/json

{
  "name": "Viajeros por el mundo"
}

###OBTENER GRUPOS
GET http://localhost:3030/api/group/


### Obtener GRUPO por su id
GET http://localhost:3030/api/group/1



### Modificar GRUPO patch
PATCH http://localhost:3030/api/group/1
Content-Type: application/json

{
  "name": "Viaje Rio Turbio"
  
}

### Modificar GRUPO patch
DELETE  http://localhost:3030/api/group/14


### Envío de correo de prueba desde Outlook
POST http://localhost:3031/api/mail/send
Content-Type: application/json

{
    "service": "outlook",
    "user": "sandra_prueba_full@hotmail.com",
    "pass": "Prueba88",
    "to": "folmos@everycode.es",
    "subject": "prueba desde Outlook",
    "text": "esto es una prueba desde Outlook11"
}

### Envío de correo de prueba desde Gmail
POST http://localhost:3031/api/mail/send
Content-Type: application/json

{
    "service": "gmail",
    "user": "tu_correo_gmail@gmail.com",
    "pass": "tu_contraseña_gmail",
    "to": "destinatario@ejemplo.com",
    "subject": "prueba desde Gmail",
    "text": "esto es una prueba desde Gmail"
}
