##############################    ENDPOINTS USER    ##############################

### Crear / Registrar usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "firstName": "Pepe",
  "lastName": "Rodriguez",
  "phoneNumber": "66666666666",
  "email": "peperod@gmail.com",
  "password": "123456"
}

### Obtener usuarios
GET http://localhost:3000/api/user/

### Obtener usuario por su id
GET http://localhost:3000/api/user/3

##############################    ENDPOINTS USER    ##############################
